# Week 8: Recurrent Neural Networks

In the example below we will cover how to implement a recurrent neural network using TensorFlow. For this example we will use data on Bengaldeshi economic indicators from 1980-2019.

In [12]:
import numpy as np
import pandas as pd
from tensorflow import keras
from tensorflow.keras import layers
def p2f(x):
    return float(x.strip('%'))/100
bd = pd.read_csv("BD_economic_indicators.csv", converters={'GDP growth':p2f, 'Inflation rate':p2f, 'Total Investment':p2f})[['Year','GDP growth','Inflation rate','Total Investment']]
bd.head()

Year  GDP growth  Inflation rate  Total Investment
0  1980       0.031           0.154            0.1444
1  1981       0.056           0.145            0.1716
2  1982       0.032           0.129            0.1736
3  1983       0.046           0.095            0.1656
4  1984       0.042           0.104            0.1648

We will use the inflation rate and total investment to predict that GDP growth rate. 

In [130]:
X = bd[['Inflation rate','Total Investment']]
Y = bd['GDP growth']

Xtot = bd[['GDP growth', 'Inflation rate', 'Total Investment']]

Xtrain = X[0:35]
Xtest = X[35:39]
Ytrain = Y[0:35]
Ytest = Y[35:39]


We will use the pre-defined keras.layers.SimpleRNN object to build our recurrent neural network. This object implements a fully connected RNN layer where the output from a previous (time)step is fed onto the next timestep. 

In [133]:
model = keras.Sequential()

embedding = layers.Embedding(input_dim = 2, output_dim= 3) # This is 
recurrent = layers.SimpleRNN(1)
hiddenLayer = layers.Dense(3)
output = layers.Dense(1, activation = 'sigmoid')
model.add(embedding)
model.add(recurrent)
model.add(hiddenLayer)
model.add(output)
model.summary()


Model: "sequential_64"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_20 (Embedding)     (None, None, 3)           6         
_________________________________________________________________
simple_rnn_54 (SimpleRNN)    (None, 1)                 5         
_________________________________________________________________
dense_89 (Dense)             (None, 3)                 6         
_________________________________________________________________
dense_90 (Dense)             (None, 1)                 4         
Total params: 21
Trainable params: 21
Non-trainable params: 0
_________________________________________________________________


We are now ready to compile and fit our model



In [135]:
model.compile(optimizer="adam", loss = keras.losses.MSLE, metrics = [keras.metrics.KLDivergence()])
model.fit(Xtrain, Ytrain, epochs = 500)

model.weights



04 - kullback_leibler_divergence: -0.0076
Epoch 339/500
2/2 [==============================] - 0s 2ms/step - loss: 1.9319e-04 - kullback_leibler_divergence: -0.0075
Epoch 340/500
2/2 [==============================] - 0s 1ms/step - loss: 1.9156e-04 - kullback_leibler_divergence: -0.0074
Epoch 341/500
2/2 [==============================] - 0s 2ms/step - loss: 1.9012e-04 - kullback_leibler_divergence: -0.0074
Epoch 342/500
2/2 [==============================] - 0s 1ms/step - loss: 1.8856e-04 - kullback_leibler_divergence: -0.0073
Epoch 343/500
2/2 [==============================] - 0s 1ms/step - loss: 1.8711e-04 - kullback_leibler_divergence: -0.0072
Epoch 344/500
2/2 [==============================] - 0s 2ms/step - loss: 1.8551e-04 - kullback_leibler_divergence: -0.0071
Epoch 345/500
2/2 [==============================] - 0s 1ms/step - loss: 1.8414e-04 - kullback_leibler_divergence: -0.0070
Epoch 346/500
2/2 [==============================] - 0s 1ms/step - loss: 1.8270e-04 - kullback_le

[<tf.Variable 'embedding_20/embeddings:0' shape=(2, 3) dtype=float32, numpy=
 array([[-0.42772615,  0.49223292,  0.48967886],
        [ 0.03105536, -0.01288614, -0.03032122]], dtype=float32)>,
 <tf.Variable 'simple_rnn_54/simple_rnn_cell_54/kernel:0' shape=(3, 1) dtype=float32, numpy=
 array([[-1.0418837 ],
        [ 0.83823615],
        [ 1.6145585 ]], dtype=float32)>,
 <tf.Variable 'simple_rnn_54/simple_rnn_cell_54/recurrent_kernel:0' shape=(1, 1) dtype=float32, numpy=array([[-0.60514045]], dtype=float32)>,
 <tf.Variable 'simple_rnn_54/simple_rnn_cell_54/bias:0' shape=(1,) dtype=float32, numpy=array([0.4280034], dtype=float32)>,
 <tf.Variable 'dense_89/kernel:0' shape=(1, 3) dtype=float32, numpy=array([[-1.4521414 ,  0.17182674, -0.8529212 ]], dtype=float32)>,
 <tf.Variable 'dense_89/bias:0' shape=(3,) dtype=float32, numpy=array([-0.36633494,  0.27429146, -0.25573686], dtype=float32)>,
 <tf.Variable 'dense_90/kernel:0' shape=(3, 1) dtype=float32, numpy=
 array([[ 0.5715729 ],
       

In [136]:
model.predict(Xtest)

array([[0.05201671],
       [0.05201671],
       [0.05201671],
       [0.05201671]], dtype=float32)